# Site settings
title: HACKING
email: android_zhibinw#163.com
description: > # this means to ignore newlines until "baseurl:"
 If you can't explain it to a six years old, you don't understand it yourself.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zhibin_
github_username:  androidzhibinw

# Build settings
markdown: kramdown
